SELECT id,
       username,
       hash,
       age,
       weight,
       height_feet,
       height_inches,
       gender,
       exercise_history,
       fitness_goals,
       injury,
       injury_details,
       commitment,
       additional_notes,
       name,
       form_completed,
       workouts_completed,
       last_workout_completed,
       last_workout_details
FROM public.users
LIMIT 1000;